### ISSUE TITLE
[BLOQUANT] Impossible d'ouvrir un contenu (Onglet)

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#104]
Une fois le contenu chargé, dès que je double clique sur un extrait (j'ai essayé sur plusieurs, cf:log) rien ne se passe. Sauf une jolie erreur dans les log que voici:

```
....
2016-05-06 16:40:53 INFO  Configuration:163 - Espace de travail chargé en mémoire
2016-05-06 16:40:54 INFO  MdTextController:73 - PYTHON STARTED
2016-05-06 16:40:55 DEBUG MdTextController:229 - Tentative d'ouverture du contenu stocké dans D:\Kevin\Mes documents\zwriter-workspace\offline\un-mouvement-horloger-comment-est-ce-que-ca-fonctionne
2016-05-06 16:40:55 INFO  MdTextController:316 - Contenu stocké dans D:\Kevin\Mes documents\zwriter-workspace\offline\un-mouvement-horloger-comment-est-ce-que-ca-fonctionne ouvert
2016-05-06 16:40:59 DEBUG MdTextController:171 - Tentative de création d'un nouvel onglet pour Introduction
2016-05-06 16:40:59 ERROR MdTextController:249 - 
/D:/Programmation/java/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/fxml/Editor.fxml

javafx.fxml.LoadException: 
/D:/Programmation/java/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/fxml/Editor.fxml

    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2543)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at com.zestedesavoir.zestwriter.view.MdTextController.createTabExtract(MdTextController.java:175)
    at com.zestedesavoir.zestwriter.view.MdTextController.lambda$openContent$10(MdTextController.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[16,214]
Message: L'attribut "xmlns:fx" a déjà été spécifié pour l'élément "SplitPane".
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
    at javax.xml.stream.util.StreamReaderDelegate.next(StreamReaderDelegate.java:88)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2513)
    ... 36 more
2016-05-06 16:41:02 DEBUG MdTextController:171 - Tentative de création d'un nouvel onglet pour Montre à quartz
2016-05-06 16:41:02 ERROR MdTextController:249 - 
/D:/Programmation/java/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/fxml/Editor.fxml

javafx.fxml.LoadException: 
/D:/Programmation/java/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/fxml/Editor.fxml

    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2543)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at com.zestedesavoir.zestwriter.view.MdTextController.createTabExtract(MdTextController.java:175)
    at com.zestedesavoir.zestwriter.view.MdTextController.lambda$openContent$10(MdTextController.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[16,214]
Message: L'attribut "xmlns:fx" a déjà été spécifié pour l'élément "SplitPane".
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
    at javax.xml.stream.util.StreamReaderDelegate.next(StreamReaderDelegate.java:88)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2513)
    ... 36 more
2016-05-06 16:41:03 DEBUG MdTextController:171 - Tentative de création d'un nouvel onglet pour Introduction
2016-05-06 16:41:03 ERROR MdTextController:249 - 
/D:/Programmation/java/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/fxml/Editor.fxml

javafx.fxml.LoadException: 
/D:/Programmation/java/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/fxml/Editor.fxml

    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2543)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at com.zestedesavoir.zestwriter.view.MdTextController.createTabExtract(MdTextController.java:175)
    at com.zestedesavoir.zestwriter.view.MdTextController.lambda$openContent$10(MdTextController.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[16,214]
Message: L'attribut "xmlns:fx" a déjà été spécifié pour l'élément "SplitPane".
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
    at javax.xml.stream.util.StreamReaderDelegate.next(StreamReaderDelegate.java:88)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2513)
    ... 36 more
```

Cela ne venait pas de la PR de @artragis comme je l'avais imaginé, mais de plus haut dans la branche master.

**Comment by firm1** [comment]
Très bizarre comme bug. Sur la master je n'ai pas eu ce problème pourtant. De plus l'erreur est assez etrange. Elle incrimine [cette ligne](https://github.com/firm1/zest-writer/blob/master/src/main/resources/com/zestedesavoir/zestwriter/fxml/Editor.fxml#L16) qui est pourtant correcte normalement.

**Comment by WinXaito** [comment]
Effectivement, surtout qu'elle n'a pas été modifié récemment.

Tu as moyen de compiler et voir si tu as le problème ? Si tu n'as rien, je retenterai un clone et une compilation.

**Comment by firm1** [comment]
Là tout de suite non. Mais ce matin, je suis a peu près certain que sur la master je n'avais pas de problème.

**Comment by WinXaito** [comment]
Bon c'est ce que je craignais, si je clone ton repo (L'officiel), je compile sans problème, mais si je prend le mien j'ai ce problème.

A première vu je dirais que c'est un problème de cache de gradle (Avec l'externalisation zMarkdown), je vais continuer de chercher de ce côté.

**Comment by WinXaito** [comment]
Bon effectivement c'était bien ça.

Par contre la j'ai un petit problème, j'ai tous les accents qui ont lâché ...

**Comment by firm1** [comment]
lâché ? c'est à dire ?

**Comment by WinXaito** [comment]
`Ã©`

J'ai ce genre de signe à tout les endroits où il y a un accent, y compris dans les logs.

**Comment by firm1** [comment]
Ton souci ressemble fortement a un problème d'encodage. Tu es sur que ton EDI est bien parametré ? Parce que de mon coté je n'ai pas de souci.

Vérifie aussi le formattage par défaut de git chez toi.

**Comment by firm1** [comment]
Du coup @WinXaito tu as pu regarder ça ?

**Comment by WinXaito** [comment]
Nop, jusqu'à jeudi soir comme d'hab je pourrai pas faire grand chose. Mais sinon bon boulot pour les hotfix de ce que j'ai pu voir.

**Comment by firm1** [comment]
J'ai vraiment l'impression ici que c'est ton encodage qui foire. Parce que j'ai refait un clone du projet récemment et je n'ai pas eu de souci.

**Comment by WinXaito** [comment]
Fort possible, et désolé je n'ai pas repenser a tester depuis.
