### ISSUE TITLE
Crash de l'application sur OS X

### ISSUE THREAD

**Issue by MrCirdo** [firm1/zest-writer#156]
Quand j'ouvre l'application sur OS X, l'application Crash au démarrage.

Voici les logs :

```
Exception in Application constructor
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
    at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class com.zestedesavoir.zestwriter.MainApp
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:819)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.RuntimeException: Could not create 
    at com.zestedesavoir.zestwriter.utils.LocalDirectorySaver.openDirCreateIfNecessary(LocalDirectorySaver.java:36)
    at com.zestedesavoir.zestwriter.utils.LocalDirectorySaver.<init>(LocalDirectorySaver.java:21)
    at com.zestedesavoir.zestwriter.utils.LocalDirectoryFactory.<init>(LocalDirectoryFactory.java:20)
    at com.zestedesavoir.zestwriter.utils.Configuration.loadWorkspace(Configuration.java:162)
    at com.zestedesavoir.zestwriter.utils.Configuration.initConf(Configuration.java:111)
    at com.zestedesavoir.zestwriter.utils.Configuration.<init>(Configuration.java:41)
    at com.zestedesavoir.zestwriter.MainApp.<init>(MainApp.java:62)
    ... 10 more
Exception running application com.zestedesavoir.zestwriter.MainApp
logout
```

**Comment by WinXaito** [comment]
Pouep, ça me plaît pas trop, car on a pas beaucoup d'indice sur ces logs de crash.

Tu l'as ouvert avec le `DMG` ? 

Si oui:
- Essaye de lancer le JAR seul
- Essaye de le lancer en mode administrateur (Ouvrir console en mode admin et ensuite `java -jar "chemin/au/jar"`)

**Comment by MrCirdo** [comment]
J'ai testé depuis le .jar. Pareil l'appli crash. Je te met les logs:

Sans le sudo 

```
Exception in Application constructor
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:367)
    at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:305)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class com.zestedesavoir.zestwriter.MainApp
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:884)
    at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
    at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at com.sun.javafx.application.LauncherImpl$7.run(LauncherImpl.java:791)
    at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.RuntimeException: Could not create
    at com.zestedesavoir.zestwriter.utils.LocalDirectorySaver.openDirCreateIfNecessary(LocalDirectorySaver.java:36)
    at com.zestedesavoir.zestwriter.utils.LocalDirectorySaver.<init>(LocalDirectorySaver.java:21)
    at com.zestedesavoir.zestwriter.utils.LocalDirectoryFactory.<init>(LocalDirectoryFactory.java:20)
    at com.zestedesavoir.zestwriter.utils.Configuration.loadWorkspace(Configuration.java:162)
    at com.zestedesavoir.zestwriter.utils.Configuration.initConf(Configuration.java:111)
    at com.zestedesavoir.zestwriter.utils.Configuration.<init>(Configuration.java:41)
    at com.zestedesavoir.zestwriter.MainApp.<init>(MainApp.java:62)
    ... 11 more
```

Et avec le sudo (eh oui il y a un petit changement):

```
2016-06-28 21:40:30 DEBUG Configuration:104 - le fichier de configuartion /var/root/.zestwriter/conf.properties n'existe pas
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 INFO  Configuration:129 - Fichier de configuration enregistré
2016-06-28 21:40:32 DEBUG Configuration:77 - le fichier des actions /var/root/.zestwriter/action.properties n'existe pas
2016-06-28 21:40:32 INFO  Configuration:138 - Fichier d'actions enregistré
Jun 28, 2016 9:40:34 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.40 by JavaFX runtime of version 8.0.5
Exception in Application start method
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:367)
    at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:305)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:894)
    at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
    at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: tried to access method com.sun.javafx.css.parser.CSSParser.<init>()V from class de.jensd.fx.glyphs.GlyphIcon
    at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:49)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:433)
    at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1010)
    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:740)
    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2723)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at com.zestedesavoir.zestwriter.view.com.CustomFXMLLoader.load(CustomFXMLLoader.java:19)
    at com.zestedesavoir.zestwriter.MainApp.initRootLayout(MainApp.java:165)
    at com.zestedesavoir.zestwriter.MainApp.start(MainApp.java:142)
    at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
    at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application com.zestedesavoir.zestwriter.MainApp
```

**Comment by GerardPaligot** [comment]
Aucun problème sur mon OS X 10.9.5.

**Comment by WinXaito** [comment]
Quelle est ta version de Java ? Car j'ai un doute la dessus `WARNING: Loading FXML document with JavaFX API of version 8.0.40 by JavaFX runtime of version 8.0.5`

Tu dois bien avoir Java 8 d'installé.

Edit: Bon j'ai quand même un doute, puisque @firm1 inclu le Runtime avec..

**Comment by MrCirdo** [comment]
@WinXaito Oui, j'ai bien java 8 (Mise à jour 91 d'après le panneau)

 Je vais essayer de  remettre l'application à zero. Où sont stockés les fichiers que créé l'app ?

**Comment by WinXaito** [comment]
Sur Windows, l'installation installe l'app dans `C:/Program files...`. je ne connais pas son équivalent sur Mac.

Mais je doute que ça vienne de la. Tu peux tenter de supprimer les fichiers de configuration qui doivent être dans le dossier `.zestwriter` dans ton home.

**Comment by MrCirdo** [comment]
Sur mac, tu as juste une espèce d'archive (c'est une image disque pour être précis) où tu as l'app et tu as juste à la faire glisser dans le dossier applications.

J'ai enlevé le dossier `.zestewriter`et le dossier `zeste-workspace`. Pas de changement.

**Comment by WinXaito** [comment]
C'est plus embêtant la, surtout que ça fonctionne chez Andr0.

**Comment by MrCirdo** [comment]
Je viens de tester avec une ancienne version (1.1.0) tout fonctionne à merveille.

**Comment by DevHugo** [comment]
Surement à cause de ça: [une piste](https://bitbucket.org/Jerady/fontawesomefx/issues/27/illegalaccesserror-on-fontawesomeicon).

@GerardPaligot tu es à quel maj de la jdk ?

**Comment by DevHugo** [comment]
Pour le bug sans le sudo, tu peux m'indiquer ou est situé ton workspace ? (genre si tu as besoin de droit sur le dossier, il va planter lamantable comme ici).

**Comment by GerardPaligot** [comment]
Java 8 révision 91

**Comment by DevHugo** [comment]
On parle bien de la dernière version de zestwriter ?

**Comment by firm1** [comment]
De ce que je vois du bug sans le sudo, c'est le meme pb que sur un des Windows qui crashe au demarrage aussi.

Je crois avoir reussi a identifier le souci qui vient du fait que sur certaines machines, la variable d'environnement `user.home` (qui est le repertoire par defaut de pleins de truc) de la JVM n'est pas peuplée. Il faudrait donc trouver une alternative a ce repertoire quand la JVM ne peut pad nous la donner

**Comment by firm1** [comment]
@MrCirdo je viens de pousser une PR qui devrait corriger ton souci, est-ce que tu peux télécharger le jar sur [ce lien](https://github.com/firm1/zest-writer/releases/download/1.2.0/zest-writer-all-1.2.0.jar) et le lancer s'il te plait chez toi en mode non admin ?

**Comment by MrCirdo** [comment]
C'est bon ça fonctionne 👍

**Comment by firm1** [comment]
Buenooo
