### ISSUE TITLE
Les liens dans le menu "À propos" ne sont pas cliquable avec une jdk récente

### ISSUE THREAD

**Issue by DevHugo** [firm1/zest-writer#198]
Les liens dans le menu "À propos" ne sont pas cliquable et génère l'exception suivante:

```
java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.sun.javafx.application.HostServicesDelegate.lambda$getInstance$0(HostServicesDelegate.java:52)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.HostServicesDelegate.getInstance(HostServicesDelegate.java:45)
    at javafx.application.HostServices.<init>(HostServices.java:52)
    at javafx.application.Application.getHostServices(Application.java:334)
    at com.zestedesavoir.zestwriter.view.dialogs.AboutDialog.HandleZdsHyperlinkAction(AboutDialog.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
```

Ceci est due à une erreur de la [JDK](https://bugs.openjdk.java.net/browse/JDK-8160464) sur les jdk récente.

**Comment by firm1** [comment]
OMG. Du coup tu suis le ticket openjdk pour savoir quand c'est résolu ? ou
tu veux que je le fasse.

Le mar. 12 juil. 2016 13:40, Hugo Courtecuisse notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
J'ai un compte donc t’inquiète pas, je le ferais.

Tout manière, ça casse aucune fonctionnalité donc bon.

**Comment by firm1** [comment]
Super alors

Le mar. 12 juil. 2016 13:54, Hugo Courtecuisse notifications@github.com a
écrit :

**Comment by WinXaito** [comment]
ça serait quand même bien de capturer l'erreur et de mettre un message d'avertissement à l'utilisateur que sa version du JDK contient un bug.

**Comment by firm1** [comment]
Du coup le problème est résolu coté upstream, on peut donc fermer cette issue
